# Generated by Django 4.1.7 on 2023-03-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(default="Hello there!"),
        ),
    ]
