# Generated by Django 4.1.7 on 2023-03-01 07:57

import HousingApp.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HousingApp', '0002_alter_collection_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collections',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=HousingApp.models.Collection, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=HousingApp.models.Friend, null=True),
        ),
    ]
