# Generated by Django 4.1.7 on 2023-03-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HousingApp', '0003_alter_user_collections_alter_user_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='collections',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
