# Generated by Django 3.1.12 on 2023-03-04 05:38

import HousingApp.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('HousingApp', '0004_remove_user_collections_remove_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collections',
            field=djongo.models.fields.ArrayField(blank=True, default=[], model_container=HousingApp.models.Collection, null=True),
        ),
    ]
